### ISSUE TITLE
Problem with Google App Script?

### ISSUE THREAD

**Issue by SnorkY** [Pedrojok01/Import-CryptoData-into-GoogleSheet#1]
Hi,
Since today the script is bloqued, I don't know why... 
I haven't changed anything, it always worked for CoinGecko.

When I run the script update I have error message :
**TypeError: responses.getResponseCode is not a function**

**Comment by Pedrojok01** [comment]
Hi Snorky, 
Yeah, seems like there is an issue since today, I've been getting some nasty "error 403" on my side. But their server is up and running. Not sure where the issue comes from yet. Will try to find a fix in the coming days.
In the meantime, you can try to switch to the coin paprika script. I know it's a pain, but it should be working.

**Comment by SnorkY** [comment]
No problem, I'm patient.
Thank you again for your work!
He also teaches me how to script on Google Sheets!

Thanks thanks thanks ;-)


Le mer. 28 juil. 2021 à 14:00, Pedrojok01 ***@***.***> a
écrit :

**Comment by SnorkY** [comment]
Looks like CoinGecko blocked IP server Google app script ...


Le mer. 28 juil. 2021 à 14:02, Hugo Meilleur ***@***.***> a
écrit :

**Comment by Pedrojok01** [comment]
Yep, seems right about the requests blocked from Coingecko. Wondering if cryptosheets also have this issue. 
Not sure how to work that out. Unless someone smarter comes here with some help, I think the best would be to switch to CoinPaprika API for now.

EDIT: just checked again, everything is back to normal. So the issue was on their end after all! Very nice :)
